In [1]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import layers
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.model_selection import train_test_split

2024-09-30 10:40:27.093758: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-30 10:40:27.282591: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-30 10:40:27.459407: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-30 10:40:27.603493: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-30 10:40:27.652402: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-30 10:40:27.937202: I tensorflow/core/platform/cpu_feature_gu

In [2]:
from seaborn import load_dataset

df = load_dataset("iris")

In [3]:
df["species"] = df["species"].map({"setosa": 0, "versicolor": 1, "virginica": 2})

In [4]:
X, y = df.loc[:, df.columns != "species"], df["species"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, shuffle=True)

In [5]:
model = keras.Sequential(
    [
        layers.Dense(units=25, activation="relu"),
        layers.Dense(units=15, activation="relu"),
        layers.Dense(units=3, activation="linear"),
    ]
)

# Adam optimizer instead of Gradient Descent

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss=SparseCategoricalCrossentropy(from_logits=True),
)

In [11]:
# Round OFF Error

print(
    "Here Both Terms Should Return Same Result But First One Do Not Produce So Because Of Round off Error, Second One Is More Accurate"
)
print("1) 2 / 10000 =", 2 / 10000)

print("2) 1 + (1 / 10000) - (1 - 1 / 10000) =", 1 + (1 / 10000) - (1 - 1 / 10000))

Here Both Terms Should Return Same Result But First One Do Not Produce So Because Of Round off Error, Second One Is More Accurate
1) 2 / 10000 = 0.0002
2) 1 + (1 / 10000) - (1 - 1 / 10000) = 0.00019999999999997797


In [6]:
# Start loss will be : 0.0059
model.fit(X_test, y_test, epochs=400)

Epoch 1/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 1.9095  
Epoch 2/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7742 
Epoch 3/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5739 
Epoch 4/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4849 
Epoch 5/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3403 
Epoch 6/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2428 
Epoch 7/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1593 
Epoch 8/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0895 
Epoch 9/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0413 
Epoch 10/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9855 
Epoch 11/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9390 
Epoch 12/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8918 
Epoch 13/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8658 
Epoch 14/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8355 
Epoch 15/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8051 
Epoch 16/400
2/2 ━

In [7]:
y_pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


In [8]:
y_pred

array([[ -4.375303  ,   3.0090806 ,   0.887693  ],
       [  4.470442  ,  -1.5983429 , -13.103614  ],
       [-10.480229  ,   5.4549    ,  11.276161  ],
       [ -4.3116326 ,   2.7743168 ,   1.3068675 ],
       [ -4.622773  ,   3.206082  ,   0.87930197],
       [  4.155223  ,  -1.4580842 , -12.156564  ],
       [ -2.1526744 ,   1.8475052 ,  -2.2419918 ],
       [ -6.243243  ,   3.3813043 ,   4.854422  ],
       [ -5.3319235 ,   3.353237  ,   3.1004977 ],
       [ -2.9008527 ,   2.2994308 ,  -1.3004004 ],
       [ -5.7650642 ,   3.2165408 ,   3.9583113 ],
       [  3.8154144 ,  -1.3672259 , -11.28453   ],
       [  4.3680797 ,  -1.5898553 , -13.056331  ],
       [  3.8834076 ,  -1.3881146 , -11.44101   ],
       [  4.2189217 ,  -1.5185809 , -12.407416  ],
       [ -4.1552815 ,   2.6883314 ,   0.73497415],
       [ -7.9519615 ,   4.053432  ,   8.123619  ],
       [ -3.1410646 ,   2.4046233 ,  -0.7331995 ],
       [ -4.2705846 ,   2.793468  ,   1.2827549 ],
       [ -7.8702717 ,   4.01593

In [9]:
y_pred_softmax = tf.nn.softmax(y_pred)

In [10]:
tf.nn.softmax(y_pred)

<tf.Tensor: shape=(38, 3), dtype=float32, numpy=
array([[5.54110913e-04, 8.92469823e-01, 1.06976047e-01],
       [9.97691393e-01, 2.30864156e-03, 2.32638317e-08],
       [3.54841739e-10, 2.95510539e-03, 9.97044802e-01],
       [6.79563324e-04, 8.12117100e-01, 1.87203318e-01],
       [3.62548337e-04, 9.10740554e-01, 8.88969600e-02],
       [9.96364117e-01, 3.63571476e-03, 8.20916810e-08],
       [1.76920630e-02, 9.66127634e-01, 1.61803700e-02],
       [1.23229202e-05, 1.86466888e-01, 8.13520789e-01],
       [9.51556212e-05, 5.62797010e-01, 4.37107772e-01],
       [5.33962948e-03, 9.68201041e-01, 2.64593251e-02],
       [4.05516330e-05, 3.22604001e-01, 6.77355409e-01],
       [9.94417965e-01, 5.58183482e-03, 2.75262209e-07],
       [9.97421324e-01, 2.57857889e-03, 2.70118043e-08],
       [9.94890273e-01, 5.10954531e-03, 2.20021434e-07],
       [9.96787429e-01, 3.21245356e-03, 5.99618915e-08],
       [9.32958792e-04, 8.74995232e-01, 1.24071896e-01],
       [1.02591493e-07, 1.67875569e-02,

In [12]:
import numpy as np

array = []
for item in y_pred_softmax:
    array.append(np.argmax(item))
y_pred_array = np.array(array)

In [13]:
y_pred_array

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [14]:
from sklearn.metrics import f1_score, precision_score, recall_score

print(f1_score(y_test, y_pred_array, average="macro"))
print(precision_score(y_test, y_pred_array, average="macro"))
print(recall_score(y_test, y_pred_array, average="macro"))

1.0
1.0
1.0
