In [30]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import layers
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.model_selection import train_test_split

In [33]:
from seaborn import load_dataset

df = load_dataset("iris")

In [34]:
df["species"] = df["species"].map({"setosa": 0, "versicolor": 1, "virginica": 2})

In [35]:
X, y = df.loc[:, df.columns != "species"], df["species"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, shuffle=True)

In [36]:
model = keras.Sequential(
    [
        layers.Dense(units=25, activation="relu"),
        layers.Dense(units=15, activation="relu"),
        layers.Dense(units=3, activation="linear"),
    ]
)

model.compile(loss=SparseCategoricalCrossentropy(from_logits=True))

In [11]:
# Round OFF Error

print(
    "Here Both Terms Should Return Same Result But First One Do Not Produce So Because Of Round off Error, Second One Is More Accurate"
)
print("1) 2 / 10000 =", 2 / 10000)

print("2) 1 + (1 / 10000) - (1 - 1 / 10000) =", 1 + (1 / 10000) - (1 - 1 / 10000))

Here Both Terms Should Return Same Result But First One Do Not Produce So Because Of Round off Error, Second One Is More Accurate
1) 2 / 10000 = 0.0002
2) 1 + (1 / 10000) - (1 - 1 / 10000) = 0.00019999999999997797


In [38]:
# Start loss will be : 0.0059
model.fit(X_test, y_test, epochs=400)

Epoch 1/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0993 
Epoch 2/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1121 
Epoch 3/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1026 
Epoch 4/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1156 
Epoch 5/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1150 
Epoch 6/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1063 
Epoch 7/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1054 
Epoch 8/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1081 
Epoch 9/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1059 
Epoch 10/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1084 
Epoch 11/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1064 
Epoch 12/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1017 
Epoch 13/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1051 
Epoch 14/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1063 
Epoch 15/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1074 
Epoch 16/400
2/2 ━━

In [39]:
y_pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


In [40]:
y_pred

array([[ -5.9998865 ,   5.134643  ,   0.95224607],
       [ 22.543194  ,  12.801774  , -12.452786  ],
       [-23.800274  ,   1.560267  ,   9.482148  ],
       [ -7.2797165 ,   4.4218607 ,   1.7870227 ],
       [ -6.2985725 ,   5.3472795 ,   1.0341398 ],
       [ 20.776794  ,  11.80924   , -11.498966  ],
       [ -0.41905963,   5.838127  ,  -1.4089752 ],
       [-15.141325  ,   2.472571  ,   5.7297997 ],
       [ -9.646424  ,   3.5994272 ,   2.8664224 ],
       [ -1.8036    ,   5.711801  ,  -0.88940823],
       [-13.215257  ,   3.0578613 ,   4.729384  ],
       [ 19.48839   ,  11.149821  , -10.854811  ],
       [ 22.31763   ,  12.540091  , -12.228856  ],
       [ 19.805353  ,  11.357876  , -11.048772  ],
       [ 21.6711    ,  12.147126  , -11.854926  ],
       [ -6.9182115 ,   4.871875  ,   1.5806266 ],
       [-20.189571  ,   1.2960176 ,   8.084244  ],
       [ -2.3805718 ,   5.434579  ,  -0.6258763 ],
       [ -6.820296  ,   4.4959164 ,   1.5210942 ],
       [-19.67543   ,   1.25759

In [42]:
y_pred_softmax = tf.nn.softmax(y_pred)

In [44]:
tf.nn.softmax(y_pred)

<tf.Tensor: shape=(38, 3), dtype=float32, numpy=
array([[1.4379745e-05, 9.8495346e-01, 1.5032245e-02],
       [9.9994117e-01, 5.8793539e-05, 6.3301461e-16],
       [3.5113219e-15, 3.6258783e-04, 9.9963737e-01],
       [7.7264613e-06, 9.3306309e-01, 6.6929162e-02],
       [8.6395212e-06, 9.8677689e-01, 1.3214360e-02],
       [9.9987268e-01, 1.2746340e-04, 9.6108085e-15],
       [1.9116044e-03, 9.9737793e-01, 7.1036775e-04],
       [8.3057994e-10, 3.7067991e-02, 9.6293187e-01],
       [1.1939927e-06, 6.7546350e-01, 3.2453531e-01],
       [5.4359686e-04, 9.9810010e-01, 1.3561428e-03],
       [1.3550003e-08, 1.5822129e-01, 8.4177876e-01],
       [9.9976087e-01, 2.3905718e-04, 6.6376063e-14],
       [9.9994320e-01, 5.6707904e-05, 9.9226373e-16],
       [9.9978566e-01, 2.1439473e-04, 3.9822658e-14],
       [9.9992687e-01, 7.3073294e-05, 2.7529568e-15],
       [7.3073784e-06, 9.6412027e-01, 3.5872381e-02],
       [5.2522927e-13, 1.1256975e-03, 9.9887431e-01],
       [4.0247253e-04, 9.9727070e

In [51]:
import numpy as np

array = []
for item in y_pred_softmax:
    array.append(np.argmax(item)), average="macro"
y_pred_array = np.array(array)

In [52]:
y_pred_array

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [56]:
from sklearn.metrics import f1_score, precision_score, recall_score

print(f1_score(y_test, y_pred_array, average="macro"))
print(precision_score(y_test, y_pred_array, average="macro"))
print(recall_score(y_test, y_pred_array, average="macro"))

1.0
1.0
1.0
